uploads = []
outputs = []

[[generated]]
id = "2LDgJDXwkfVfgoY8rjEyi"
uri = "file://public/characters/default-self.png"
type = "image"
title = "generated_image"

[[generated]]
id = "FreKYO17QL5wZw6VLH_Cv"
uri = "file://public/characters/default-opponent.png"
type = "image"
title = "generated_image"

[[generated]]
id = "409kNtpleW5KenJuCi6m2"
uri = "file://public/images/battle-modes/quick-match.png"
type = "image"
title = "quick match speed art"

[[generated]]
id = "klQd28g77Sxe7GG1-6z8h"
uri = "file://public/images/battle-modes/challenge-friend.png"
type = "image"
title = "challenge friend clash art"

[[generated]]
id = "AWGDFIR-p9Ieb7AAr6gsg"
uri = "file://public/images/battle-modes/private-match.png"
type = "image"
title = "private match vault art"
