const teamLogos = {
  'Arizona Diamondbacks': '/mlb/ARI.png',
  'Atlanta Braves': '/mlb/ATL.png',
  'Baltimore Orioles': '/mlb/BAL.png',
  'Chicago Cubs': '/mlb/CHC.png',
  'Cincinnati Reds': '/mlb/CIN.png',
  'Colorado Rockies': '/mlb/COL.png',
  'Detroit Tigers': '/mlb/DET.png',
  'Houston Astros': '/mlb/HOU.png',
  'Kansas City Royals': '/mlb/KC.png',
  'Los Angeles Angels': '/mlb/LAA.png',
  'Los Angeles Dodgers': '/mlb/LAD.png',
  'Miami Marlins': '/mlb/MIA.png',
  'Milwaukee Brewers': '/mlb/MIL.png',
  'Minnesota Twins': '/mlb/MIN.png',
  'New York Mets': '/mlb/NYM.png',
  'New York Yankees': '/mlb/NYY.png',
  'Oakland Athletics': '/mlb/OAK.png',
  'Philadelphia Phillies': '/mlb/PHI.png',
  'Pittsburgh Pirates': '/mlb/PIT.png',
  'San Diego Padres': '/mlb/SD.png',
  'Seattle Mariners': '/mlb/SEA.png',
  'San Francisco Giants': '/mlb/SF.png',
  'St. Louis Cardinals': '/mlb/STL.png',
  'Tampa Bay Rays': '/mlb/TB.png',
  'Texas Rangers': '/mlb/TEX.png',
  'Washington Nationals': '/mlb/WSH.png',
};

export default teamLogos;
