const teamLogos = {
  ATL: "/logos/mlb/ATL.png",
  BAL: "/logos/mlb/BAL.png",
  BOS: "/logos/mlb/BOS.png",
  CHC: "/logos/mlb/CHC.png",
  CWS: "/logos/mlb/CWS.png",
  CIN: "/logos/mlb/CIN.png",
  CLE: "/logos/mlb/CLE.png",
  COL: "/logos/mlb/COL.png",
  DET: "/logos/mlb/DET.png",
  HOU: "/logos/mlb/HOU.png",
  KC:  "/logos/mlb/KC.png",
  LAA: "/logos/mlb/LAA.png",
  LAD: "/logos/mlb/LAD.png",
  MIA: "/logos/mlb/MIA.png",
  MIL: "/logos/mlb/MIL.png",
  MIN: "/logos/mlb/MIN.png",
  NYM: "/logos/mlb/NYM.png",
  NYY: "/logos/mlb/NYY.png",
  OAK: "/logos/mlb/OAK.png",
  PHI: "/logos/mlb/PHI.png",
  PIT: "/logos/mlb/PIT.png",
  SD:  "/logos/mlb/SD.png",
  SEA: "/logos/mlb/SEA.png",
  SF:  "/logos/mlb/SF.png",
  STL: "/logos/mlb/STL.png",
  TB:  "/logos/mlb/TB.png",
  TEX: "/logos/mlb/TEX.png",
  TOR: "/logos/mlb/TOR.png",
  WSH: "/logos/mlb/WSH.png",

  // Optional: KBO team logos
  KIA: "/logos/kbo/KIA.png",
  DOO: "/logos/kbo/DOO.png",
  LOT: "/logos/kbo/LOT.png",
  HAN: "/logos/kbo/HAN.png",
  KTW: "/logos/kbo/KTW.png",
  LG:  "/logos/kbo/LG.png",
  NC:  "/logos/kbo/NC.png",
  SAM: "/logos/kbo/SAM.png",
  SK:  "/logos/kbo/SK.png",
  HHE: "/logos/kbo/HHE.png"
};

export default teamLogos;
