const teamLogos = {
  'Arizona Diamondbacks': '/logos/mlb/ari.png',
  'Atlanta Braves': '/logos/mlb/atl.png',
  'Baltimore Orioles': '/logos/mlb/bal.png',
  'Boston Red Sox': '/logos/mlb/bos.png',
  'Chicago Cubs': '/logos/mlb/chc.png',
  'Chicago White Sox': '/logos/mlb/chw.png',
  'Cincinnati Reds': '/logos/mlb/cin.png',
  'Cleveland Guardians': '/logos/mlb/cle.png',
  'Colorado Rockies': '/logos/mlb/col.png',
  'Detroit Tigers': '/logos/mlb/det.png',
  'Houston Astros': '/logos/mlb/hou.png',
  'Kansas City Royals': '/logos/mlb/kc.png',
  'Los Angeles Angels': '/logos/mlb/laa.png',
  'Los Angeles Dodgers': '/logos/mlb/lad.png',
  'Miami Marlins': '/logos/mlb/mia.png',
  'Milwaukee Brewers': '/logos/mlb/mil.png',
  'Minnesota Twins': '/logos/mlb/min.png',
  'New York Mets': '/logos/mlb/nym.png',
  'New York Yankees': '/logos/mlb/nyy.png',
  'Oakland Athletics': '/logos/mlb/oak.png',
  'Philadelphia Phillies': '/logos/mlb/phi.png',
  'Pittsburgh Pirates': '/logos/mlb/pit.png',
  'San Diego Padres': '/logos/mlb/sd.png',
  'San Francisco Giants': '/logos/mlb/sf.png',
  'Seattle Mariners': '/logos/mlb/sea.png',
  'St. Louis Cardinals': '/logos/mlb/stl.png',
  'Tampa Bay Rays': '/logos/mlb/tb.png',
  'Texas Rangers': '/logos/mlb/tex.png',
  'Toronto Blue Jays': '/logos/mlb/tor.png',
  'Washington Nationals': '/logos/mlb/wsh.png',
};

export default teamLogos;
